version: '2'
services:
  consul:
    image: autopilotpattern/consul:latest
    restart: always
    dns:
      - 127.0.0.1
  influx:
    image: tutum/influxdb:latest
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always
  serializer:
    build: ./serializer
    environment:
      - PORT=10000
    expose:
      - "10000"
    restart: always
  frontend:
    build: ./frontend
    environment:
      - PORT=10001
    ports:
      - 10001:10001
    restart: always
  temperature:
    build: ./temperature
    expose:
      - "8080"
    environment:
      - PORT=8080
    env_file:
      - sensors.env
    restart: always
  motion:
    build: ./motion
    expose:
      - "8080"
    environment:
      - PORT=8080
    env_file:
      - sensors.env
    restart: always
  humidity:
    build: ./humidity
    expose:
      - "8080"
    environment:
      - PORT=8080
    env_file:
      - sensors.env
    restart: always

