version: "2"
services:
  consul:
    extends:
      file: docker-compose.yml
      service: consul
    ports:
      - "8500:8500"
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir /ui
  influx:
    extends:
      file: docker-compose.yml
      service: influx
    environment:
      - PRE_CREATE_DB=temperature;humidity;motion;
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
  serializer:
    extends:
      file: docker-compose.yml
      service: serializer
    links:
      - consul:consul
      - influx:influx
    environment:
      - CONSUL_HOST=consul
      - INFLUXDB_USER=root
      - INFLUXDB_PWD=root
  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
  temperature:
    extends:
      file: docker-compose.yml
      service: temperature
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
  motion:
    extends:
      file: docker-compose.yml
      service: motion
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
  humidity:
    extends:
      file: docker-compose.yml
      service: humidity
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul