consul:
  extends:
    file: docker-compose.yml
    service: consul
  labels:
    - triton.cns.services=consul
  mem_limit: 128m
  command: >
    /usr/local/bin/containerpilot
    /bin/consul agent -server
      -bootstrap-expect 3
      -config-dir=/etc/consul
      -ui-dir /ui
CONSUL=consul.svc.$(triton account get | awk -F": " '/id:/{print $2}').$(triton profile get | awk -F"/" '/url:/{print $3}' | awk -F'.' '{print $1}').cns.joyent.com