version: '2'
services:
  consul:
    image: autopilotpattern/consul:latest
    restart: always
    dns:
      - 127.0.0.1
    ports:
      - "8500:8500"
    command: >
      /usr/local/bin/containerpilot
      /bin/consul agent -server
        -bootstrap-expect 1
        -config-dir=/etc/consul
        -ui-dir /ui
  influx:
    image: tutum/influxdb:latest
    ports:
      - "8086:8086"
      - "8083:8083"
    restart: always
    environment:
      - PRE_CREATE_DB=temperature;humidity;motion;
      - ADMIN_USER=root
      - INFLUXDB_INIT_PWD=root
  serializer:
    build: ./serializer
    links:
      - consul:consul
      - influx:influx
    environment:
      - PORT=10000
      - CONSUL_HOST=consul
      - INFLUXDB_USER=root
      - INFLUXDB_PWD=root
    expose:
      - "10000"
    restart: always
  frontend:
    build: ./frontend
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
      - PORT=10001
    ports:
      - 10001:10001
    restart: always
  temperature:
    build: ./temperature
    expose:
      - "8080"
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
      - PORT=8080
    env_file:
      - sensors.env
    restart: always
  motion:
    build: ./motion
    expose:
      - "8080"
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
      - PORT=8080
    env_file:
      - sensors.env
    restart: always
  humidity:
    build: ./humidity
    expose:
      - "8080"
    links:
      - consul:consul
    environment:
      - CONSUL_HOST=consul
      - PORT=8080
    env_file:
      - sensors.env
    restart: always

